### ISSUE TITLE
"TypeError: Object of type Message is not JSON serializable" while using Azure endpoint as LLM backend

### ISSUE THREAD

**Issue by Vinayak21574** [letta-ai/letta#1455]
**The bug**
I am encountering a TypeError when initiating interactions with the MemGPT agent (either newly created or already existing). The error indicates that an object of type Message is not JSON serializable. Below is the error traceback:

```
An exception occurred when running agent.step(): 
Traceback (most recent call last):
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/main.py", line 408, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/main.py", line 377, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/agent.py", line 818, in step
    raise e
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/agent.py", line 733, in step
    response = self._get_ai_reply(
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/agent.py", line 451, in _get_ai_reply
    raise e
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/agent.py", line 426, in _get_ai_reply
    response = create(
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/llm_api/llm_api_tools.py", line 133, in wrapper
    raise e
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/llm_api/llm_api_tools.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/llm_api/llm_api_tools.py", line 238, in create
    return azure_openai_chat_completions_request(
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/llm_api/azure_openai.py", line 121, in azure_openai_chat_completions_request
    raise e
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/memgpt/llm_api/azure_openai.py", line 100, in azure_openai_chat_completions_request
    response = requests.post(url, headers=headers, json=data)
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/requests/models.py", line 370, in prepare
    self.prepare_body(data, files, json)
  File "/media/vinayaks/OS/Users/vinay/Documents/FILES/IIITD/LLM/Azure/env/lib/python3.10/site-packages/requests/models.py", line 510, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Message is not JSON serializable
```

**Please describe your setup**
- [ ] I installed memgpt via
  - `pip install pymemgpt`
- [ ] Describing my setup
  - OS:`Ubuntu`
  - Running  `memgpt` via `Terminal`
  - `Python` version  `3.10.12`

**MemGPT Config**
Below is my `~/.memgpt/config` file attached for your reference.

```
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-4
model_endpoint = https://sef-iiitd-openai.openai.azure.com/
model_endpoint_type = azure
context_window = 8192

[embedding]
embedding_endpoint_type = azure
embedding_endpoint = https://sef-iiitd-openai.openai.azure.com/
embedding_model = text-embedding-ada-002
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = postgres
path = /home/vinayaks/.memgpt/chroma
uri = postgresql+pg8000://postgres:password@localhost:5432/azure_memgpt

[recall_storage]
type = postgres
path = /home/vinayaks/.memgpt
uri = postgresql+pg8000://postgres:password@localhost:5432/azure_memgpt

[metadata_storage]
type = postgres
path = /home/vinayaks/.memgpt
uri = postgresql+pg8000://postgres:password@localhost:5432/azure_memgpt

[version]
memgpt_version = 0.3.17

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

```
---

**Comment by ljhskyso** [comment]
got exactly the same issue. how can we get around this?

**Comment by ljhskyso** [comment]
a fix is submitted for PR @ https://github.com/cpacker/MemGPT/pull/1495
