### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: toolmodel.user_id

### ISSUE THREAD

**Issue by RuchiLamichhane** [letta-ai/letta#1529]
**I am trying to run server as *memgpt server* and  encounter following issue:**

Traceback (most recent call last):
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: toolmodel.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mirage/wiseyak/dipesh/ntc-chatbot/backend/app/dependencies/long_term_memory/MemGPT/test.py", line 4, in <module>
    client = create_client()
  File "/home/mirage/wiseyak/dipesh/ntc-chatbot/backend/app/dependencies/long_term_memory/MemGPT/memgpt/client/client.py", line 63, in create_client
    return LocalClient()
  File "/home/mirage/wiseyak/dipesh/ntc-chatbot/backend/app/dependencies/long_term_memory/MemGPT/memgpt/client/client.py", line 709, in __init__
    add_default_presets(self.user_id, ms)
  File "/home/mirage/wiseyak/dipesh/ntc-chatbot/backend/app/dependencies/long_term_memory/MemGPT/memgpt/presets/presets.py", line 144, in add_default_presets
    add_default_tools(user_id=user_id, ms=ms)
  File "/home/mirage/wiseyak/dipesh/ntc-chatbot/backend/app/dependencies/long_term_memory/MemGPT/memgpt/presets/presets.py", line 70, in add_default_tools
    existing_tool = ms.get_tool(tool.name)
  File "/home/mirage/wiseyak/dipesh/ntc-chatbot/backend/app/dependencies/long_term_memory/MemGPT/memgpt/utils.py", line 531, in wrapper
    return func(*args, **kwargs)
  File "/home/mirage/wiseyak/dipesh/ntc-chatbot/backend/app/dependencies/long_term_memory/MemGPT/memgpt/metadata.py", line 685, in get_tool
    results = session.query(ToolModel).filter(ToolModel.name == tool_name).filter(ToolModel.user_id == None).all()
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
    return self._execute_internal(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2236, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/mirage/wiseyak/subin/dip_ntc_chatbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: toolmodel.user_id
[SQL: SELECT toolmodel.name AS toolmodel_name, toolmodel.id AS toolmodel_id, toolmodel.tags AS toolmodel_tags, toolmodel.source_type AS toolmodel_source_type, toolmodel.source_code AS toolmodel_source_code, toolmodel.module AS toolmodel_module, toolmodel.json_schema AS toolmodel_json_schema, toolmodel.user_id AS toolmodel_user_id 
FROM toolmodel 
WHERE toolmodel.name = ? AND toolmodel.user_id IS NULL]
[parameters: ('archival_memory_insert',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**I have installed memgpt as: **
  - `pip install pymemgpt`
  - Linux os

**MemGPT Config**
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = dolphin2.2-mistral:7b-q6_K
model_endpoint = http://localhost:11434
model_endpoint_type = ollama
model_wrapper = chatml
context_window = 8192

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = http://localhost:8026
embedding_model = BAAI/bge-m3
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /home/mirage/.memgpt/chroma

[recall_storage]
type = sqlite
path = /home/mirage/.memgpt

[metadata_storage]
type = sqlite
path = /home/mirage/.memgpt

[version]
memgpt_version = 0.3.18

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- The exact model I am trying to use `dolphin-2.2-mistral-7b.Q6_K.gguf`
- The local LLM backend I am  using `ollama`
- My hardware for the local LLM backend `local server with RTX 4090 `

**Comment by matridyne-scott** [comment]
Seeing the same problem with Postgres as well. 
```
   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
     self._handle_dbapi_exception(
   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
     self.dialect.do_execute(
   File "/app/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
     cursor.execute(statement, parameters)
 sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column toolmodel.user_id does not exist
 LINE 1: ..., toolmodel.json_schema AS toolmodel_json_schema, toolmodel....
                                                              ^
 
 [SQL: SELECT toolmodel.name AS toolmodel_name, toolmodel.id AS toolmodel_id, toolmodel.tags AS toolmodel_tags, toolmodel.source_type AS toolmodel_source_type, toolmodel.source_code AS toolmodel_source_code, toolmodel.module AS toolmodel_module, toolmodel.json_schema AS toolmodel_json_schema, toolmodel.user_id AS toolmodel_user_id

 FROM toolmodel 
 WHERE toolmodel.name = %(name_1)s AND toolmodel.user_id IS NULL]
 [parameters: {'name_1': 'archival_memory_insert'}]
 (Background on this error at: https://sqlalche.me/e/20/f405)
with code 1
```
