### ISSUE TITLE
TypeError: SyncServer._step() missing 1 required positional argument: 'timestamp' [ non bloquant]

### ISSUE THREAD

**Issue by scenaristeur** [letta-ai/letta#1550]
When i start a new memgpt server, i've got this error today, but i never saw this before

non bloquant if we refresh server ui

```
INFO:     127.0.0.1:42710 - "POST /api/agents/d724ca99-5218-4ad5-b508-1201f801fa94/messages HTTP/1.1" 200 OK
Task exception was never retrieved
future: <Task finished name='Task-18' coro=<to_thread() done, defined at /usr/lib/python3.11/asyncio/threads.py:12> exception=TypeError("SyncServer._step() missing 1 required positional argument: 'timestamp'")>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smag/dev/MemGPT/memgpt/server/server.py", line 656, in system_message
    return self._step(user_id=user_id, agent_id=agent_id, input_message=packaged_system_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SyncServer._step() missing 1 required positional argument: 'timestamp'
```

**Comment by sarahwooders** [comment]
Can you share you MemGPT config and the version you are using? I'm not able to reproduce this issue.
