### ISSUE TITLE
Data Source Chat - The agent chat response broke after few interaction with uploaded source data

### ISSUE THREAD

**Issue by raolak** [letta-ai/letta#1926]
**Describe the bug**
I uploaded data to source and attached the source to agent. After few interactions, the char chat conversations broke. Now agent chat functionality is not working.

Here is the server side error
Sending request to https://inference.memgpt.ai/chat/completions
Response status code: 500
HTTP error occurred: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions | Status code: 500, Message: {"detail":"Internal server error (unpack): 400 Client Error: Bad Request for url: https://api.openai.com/v1/chat/completions"}
step() failed
user_message = id='message-e2573d2d-6e00-4bf9-92ff-6093f9c09834' role=<MessageRole.user: 'user'> text='{\n  "type": "user_message",\n  "message": "Can you please summarise 5 Red Flags for Churn from Ultimate Customer Success Cheat Sheet which in archival memory?",\n  "time": "2024-10-23 01:10:29 PM UTC+0000"\n}' user_id='user-00000000' agent_id='agent-7d3fc11f-aef8-4e33-b509-1f0aaed6dbac' model=None name=None created_at=datetime.datetime(2024, 10, 23, 13, 10, 29, 840415, tzinfo=datetime.timezone.utc) tool_calls=None tool_call_id=None
error = 'NoneType' object has no attribute 'status_code'
step() failed with an unrecognized exception: ''NoneType' object has no attribute 'status_code''
Letta.letta.server.server - ERROR - Error in server._step: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/letta/llm_api/helpers.py", line 22, in make_post_request
    response.raise_for_status()
  File "/app/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/letta/llm_api/llm_api_tools.py", line 70, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/letta/llm_api/llm_api_tools.py", line 166, in create
    response = openai_chat_completions_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/letta/llm_api/openai.py", line 487, in openai_chat_completions_request
    response_json = make_post_request(url, headers, data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/letta/llm_api/helpers.py", line 49, in make_post_request
    raise requests.exceptions.HTTPError(error_message) from http_err
requests.exceptions.HTTPError: HTTP error occurred: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions | Status code: 500, Message: {"detail":"Internal server error (unpack): 400 Client Error: Bad Request for url: https://api.openai.com/v1/chat/completions"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/letta/server/server.py", line 394, in _step
    step_response = letta_agent.step(
                    ^^^^^^^^^^^^^^^^^
  File "/letta/agent.py", line 923, in step
    raise e
  File "/letta/agent.py", line 830, in step
    response = self._get_ai_reply(
               ^^^^^^^^^^^^^^^^^^^
  File "/letta/agent.py", line 503, in _get_ai_reply
    raise e
  File "/letta/agent.py", line 472, in _get_ai_reply
    response = create(
               ^^^^^^^
  File "/letta/llm_api/llm_api_tools.py", line 74, in wrapper
    if http_err.response.status_code in error_codes:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
None
Letta.letta.server.server - DEBUG - Calling step_yield()

After this error ...even after reloading the agent and sending hello results in this backend error

Sending request to https://inference.memgpt.ai/chat/completions
Response status code: 500
HTTP error occurred: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions | Status code: 500, Message: {"detail":"Internal server error (unpack): 400 Client Error: Bad Request for url: https://api.openai.com/v1/chat/completions"}
step() failed
user_message = id='message-6bce21fe-6850-4d1a-8394-e9fba07aa05d' role=<MessageRole.user: 'user'> text='{\n  "type": "user_message",\n  "message": "Hello",\n  "time": "2024-10-23 01:16:20 PM UTC+0000"\n}' user_id='user-00000000' agent_id='agent-7d3fc11f-aef8-4e33-b509-1f0aaed6dbac' model=None name=None created_at=datetime.datetime(2024, 10, 23, 13, 16, 20, 30532, tzinfo=datetime.timezone.utc) tool_calls=None tool_call_id=None
error = 'NoneType' object has no attribute 'status_code'
step() failed with an unrecognized exception: ''NoneType' object has no attribute 'status_code''
Letta.letta.server.server - ERROR - Error in server._step: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/letta/llm_api/helpers.py", line 22, in make_post_request
    response.raise_for_status()
  File "/app/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/letta/llm_api/llm_api_tools.py", line 70, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/letta/llm_api/llm_api_tools.py", line 166, in create
    response = openai_chat_completions_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/letta/llm_api/openai.py", line 487, in openai_chat_completions_request
    response_json = make_post_request(url, headers, data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/letta/llm_api/helpers.py", line 49, in make_post_request
    raise requests.exceptions.HTTPError(error_message) from http_err
requests.exceptions.HTTPError: HTTP error occurred: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions | Status code: 500, Message: {"detail":"Internal server error (unpack): 400 Client Error: Bad Request for url: https://api.openai.com/v1/chat/completions"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/letta/server/server.py", line 394, in _step
    step_response = letta_agent.step(
                    ^^^^^^^^^^^^^^^^^
  File "/letta/agent.py", line 923, in step
    raise e
  File "/letta/agent.py", line 830, in step
    response = self._get_ai_reply(
               ^^^^^^^^^^^^^^^^^^^
  File "/letta/agent.py", line 503, in _get_ai_reply
    raise e
  File "/letta/agent.py", line 472, in _get_ai_reply
    response = create(
               ^^^^^^^
  File "/letta/llm_api/llm_api_tools.py", line 74, in wrapper
    if http_err.response.status_code in error_codes:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
None
Letta.letta.server.server - DEBUG - Calling step_yield()

**Comment by raolak** [comment]
Chat using uploaded data and archival memory should work reliably as this required for critical feature implementation of the app...

thank you !

**Comment by RyanSept** [comment]
I am also experiencing this

**Comment by lemorage** [comment]
Yes, I got the exact same problem, and it happened time to time

**Comment by jannech** [comment]
Same error here, after a failed function call.

**Comment by cpacker** [comment]
@RyanSept @lemorage @jannech are you all running into the same error exactly?

ie: `error = 'NoneType' object has no attribute 'status_code'`?

Are you able to share any more of your stack traces / screenshots / information about your Letta version? (are you on the latest build)

Thank you for the bug reporting, would love to help you all out with a fix

**Comment by RyanSept** [comment]
Thanks @cpacker. I'm running letta 0.5.5 and here is my error

```
INFO:     ::1:62931 - "GET /v1/agents/agent-04ea0c4a-55fb-489a-91d8-a258b4d501b1 HTTP/1.1" 200 OK
INFO:     ::1:62930 - "GET /v1/agents/agent-04ea0c4a-55fb-489a-91d8-a258b4d501b1/messages?limit=1000&msg_object=true HTTP/1.1" 200 OK
INFO:     ::1:62928 - "GET /v1/agents/agent-04ea0c4a-55fb-489a-91d8-a258b4d501b1/archival HTTP/1.1" 200 OK
/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/local_llm/utils.py:215: UserWarning: num_tokens_from_messages() is not implemented for model letta-free. See https://github.com/openai/openai-python/blob/main/chatml.md for information on how messages are converted to tokens.
  warnings.warn(
Warning: model not found. Using cl100k_base encoding.
Letta.letta.server.server - ERROR - Error in server._step: HTTP error occurred: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions | Status code: 500, Message: {"detail":"Internal server error (unpack): 400 Client Error: Bad Request for url: https://api.openai.com/v1/chat/completions"}
Traceback (most recent call last):
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/llm_api/helpers.py", line 48, in make_post_request
    response.raise_for_status()
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/server/server.py", line 456, in _step
    usage_stats = letta_agent.step(
                  ^^^^^^^^^^^^^^^^^
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/agent.py", line 833, in step
    step_response = self.inner_step(
                    ^^^^^^^^^^^^^^^^
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/agent.py", line 1042, in inner_step
    raise e
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/agent.py", line 958, in inner_step
    response = self._get_ai_reply(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/agent.py", line 576, in _get_ai_reply
    raise e
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/agent.py", line 539, in _get_ai_reply
    response = create(
               ^^^^^^^
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/llm_api/llm_api_tools.py", line 68, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/llm_api/llm_api_tools.py", line 170, in create
    response = openai_chat_completions_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/llm_api/openai.py", line 538, in openai_chat_completions_request
    response_json = make_post_request(url, headers, data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/llm_api/helpers.py", line 76, in make_post_request
    raise requests.exceptions.HTTPError(error_message) from http_err
requests.exceptions.HTTPError: HTTP error occurred: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions | Status code: 500, Message: {"detail":"Internal server error (unpack): 400 Client Error: Bad Request for url: https://api.openai.com/v1/chat/completions"}
None
/Users/ryanmarvin/.virtualenvs/project/lib/python3.11/site-packages/letta/server/rest_api/utils.py:64: UserWarning: Error getting usage data: HTTP error occurred: 500 Server Error: Internal Server Error for url: https://inference.memgpt.ai/chat/completions | Status code: 500, Message: {"detail":"Internal server error (unpack): 400 Client Error: Bad Request for url: https://api.openai.com/v1/chat/completions"}
  warnings.warn(f"Error getting usage data: {e}")
[LLMConfig(model='letta-free', model_endpoint_type='openai', model_endpoint='https://inference.memgpt.ai', model_wrapper=None, context_window=16384, put_inner_thoughts_in_kwargs=True)]
INFO:     ::1:62927 - "GET /v1/models/ HTTP/1.1" 200 OK
```

**Comment by selajuf** [comment]
+1
