### ISSUE TITLE
Blocker: Unable to recover the chat page when the chat response returns code blocks

### ISSUE THREAD

**Issue by raolak** [letta-ai/letta#1932]
**Describe the bug**
When the response contain the code block, chat page breaks . I was not able recover from this unless i delete and recreate the agent.

Here is the api  is the payload and the reponse

payload
{"messages":[{"role":"user","name":"human","text":"Give me simple stack implementation example using python"}],"stream_steps":true,"stream_tokens":true}

Reponse
data: {"id":"message-9adb14e3-3323-4561-a2f6-5c9adf3f0968","date":"2024-10-24T11:56:43+00:00","message_type":"internal_monologue","internal_monologue":"The user wishes to explore a Python example of a simple data structure - the stack. Given my knowledge of programming concepts, I can certainly help them understand this better. Here goes the techy me."}

data: {"id":"message-9adb14e3-3323-4561-a2f6-5c9adf3f0968","date":"2024-10-24T11:56:43+00:00","message_type":"function_call","function_call":{"name":"send_message","arguments":"{\n  \"message\": \"Certainly! Here's a basic implementation of a stack in Python:\\n\\n```\\nclass Stack:\\n    def __init__(self):\\n        self.stack = []\\n\\n    def push(self, item):\\n        self.stack.append(item)\\n\\n    def pop(self):\\n        if len(self.stack) < 1:\\n            return None\\n        return self.stack.pop()\\n\\n    def peek(self):\\n        return self.stack[-1] if self.stack else None\\n\\n    def is_empty(self):\\n        return not bool(self.stack)\\n```\\nThis simple `Stack` class allows you to 'push' elements onto the stack, 'pop' them off, 'peek' at the top element without removing it, and check if the stack is empty with 'is_empty'.\"\n}"}}

data: {"id":"message-26ad7f28-d793-4e9d-b1f1-87c328ebce6e","date":"2024-10-24T11:56:43+00:00","message_type":"function_return","function_return":"None","status":"success"}

data: [DONE_STEP]

data: [DONE]

ADE Console log
TypeError: Cannot assign to read only property '0' of string 'class Stack:
    def __init__(self):
        self.stack = []

    def push(self, item):
        self.stack.append(item)

    def pop(self):
        if len(self.stack) < 1:
            return None
        return self.stack.pop()

    def peek(self):
        return self.stack[-1] if self.stack else None

    def is_empty(self):
        return not bool(self.stack)
'
    at code (index-9a9c449b.js:204:14984)
    at RC (index-9a9c449b.js:38:19538)
    at AF (index-9a9c449b.js:40:44055)
    at kF (index-9a9c449b.js:40:39787)
    at pV (index-9a9c449b.js:40:39715)
    at wg (index-9a9c449b.js:40:39568)
    at y1 (index-9a9c449b.js:40:35933)
    at cR (index-9a9c449b.js:40:36737)
    at Oi (index-9a9c449b.js:38:3279)
    at index-9a9c449b.js:40:34263
overrideMethod @ console.js:288
i1 @ index-9a9c449b.js:40
o.componentDidCatch.n.callback @ index-9a9c449b.js:40
HT @ index-9a9c449b.js:38
iR @ index-9a9c449b.js:40
SF @ index-9a9c449b.js:40
uV @ index-9a9c449b.js:40
mV @ index-9a9c449b.js:40
Wi @ index-9a9c449b.js:40
cR @ index-9a9c449b.js:40
Oi @ index-9a9c449b.js:38
(anonymous) @ index-9a9c449b.js:40
setTimeout
(anonymous) @ index-9a9c449b.js:40
p4 @ index-9a9c449b.js:40
NR @ index-9a9c449b.js:40
s @ index-9a9c449b.js:40
a @ index-9a9c449b.js:40
eo @ index-9a9c449b.js:40
setData @ index-9a9c449b.js:40
onSuccess @ index-9a9c449b.js:40
g @ index-9a9c449b.js:40
Promise.then
b @ index-9a9c449b.js:40
m4 @ index-9a9c449b.js:40
fetch @ index-9a9c449b.js:40
ku @ index-9a9c449b.js:40
onSubscribe @ index-9a9c449b.js:40
subscribe @ index-9a9c449b.js:40
(anonymous) @ index-9a9c449b.js:40
V$ @ index-9a9c449b.js:38
wm @ index-9a9c449b.js:40
Fl @ index-9a9c449b.js:40
mV @ index-9a9c449b.js:40
Wi @ index-9a9c449b.js:40
cR @ index-9a9c449b.js:40
Oi @ index-9a9c449b.js:38
(anonymous) @ index-9a9c449b.js:40
Show 1 more frame
Show lessUnderstand this error
index-9a9c449b.js:59 React Router caught the following error during render TypeError: Cannot assign to read only property '0' of string 'class Stack:
    def __init__(self):
        self.stack = []

    def push(self, item):
        self.stack.append(item)

    def pop(self):
        if len(self.stack) < 1:
            return None
        return self.stack.pop()

    def peek(self):
        return self.stack[-1] if self.stack else None

    def is_empty(self):
        return not bool(self.stack)
'
    at code (index-9a9c449b.js:204:14984)
    at RC (index-9a9c449b.js:38:19538)
    at AF (index-9a9c449b.js:40:44055)
    at kF (index-9a9c449b.js:40:39787)
    at pV (index-9a9c449b.js:40:39715)
    at wg (index-9a9c449b.js:40:39568)
    at y1 (index-9a9c449b.js:40:35933)
    at cR (index-9a9c449b.js:40:36737)
    at Oi (index-9a9c449b.js:38:3279)
    at index-9a9c449b.js:40:34263 {componentStack: '\n    at code (http://192.168.64.4:30886/assets/ind…86/assets/index-9a9c449b.js:40:148114)\n    at sTe'}
overrideMethod @ console.js:288
componentDidCatch @ index-9a9c449b.js:59
o.componentDidCatch.n.callback @ index-9a9c449b.js:40
HT @ index-9a9c449b.js:38
iR @ index-9a9c449b.js:40
SF @ index-9a9c449b.js:40
uV @ index-9a9c449b.js:40
mV @ index-9a9c449b.js:40
Wi @ index-9a9c449b.js:40
cR @ index-9a9c449b.js:40
Oi @ index-9a9c449b.js:38
(anonymous) @ index-9a9c449b.js:40
setTimeout
(anonymous) @ index-9a9c449b.js:40
p4 @ index-9a9c449b.js:40
NR @ index-9a9c449b.js:40
s @ index-9a9c449b.js:40
a @ index-9a9c449b.js:40
eo @ index-9a9c449b.js:40
setData @ index-9a9c449b.js:40
onSuccess @ index-9a9c449b.js:40
g @ index-9a9c449b.js:40
Promise.then
b @ index-9a9c449b.js:40
m4 @ index-9a9c449b.js:40
fetch @ index-9a9c449b.js:40
ku @ index-9a9c449b.js:40
onSubscribe @ index-9a9c449b.js:40
subscribe @ index-9a9c449b.js:40
(anonymous) @ index-9a9c449b.js:40
V$ @ index-9a9c449b.js:38
wm @ index-9a9c449b.js:40
Fl @ index-9a9c449b.js:40
mV @ index-9a9c449b.js:40
Wi @ index-9a9c449b.js:40
cR @ index-9a9c449b.js:40
Oi @ index-9a9c449b.js:38
(anonymous) @ index-9a9c449b.js:40
Show 1 more frame
Show lessUnderstand this error
index-9a9c449b.js:40 TypeError: Cannot assign to read only property '0' of string 'Stack'
    at code (index-9a9c449b.js:204:14984)
    at RC (index-9a9c449b.js:38:19538)
    at AF (index-9a9c449b.js:40:44055)
    at kF (index-9a9c449b.js:40:39787)
    at pV (index-9a9c449b.js:40:39715)
    at wg (index-9a9c449b.js:40:39568)
    at y1 (index-9a9c449b.js:40:35933)
    at cR (index-9a9c449b.js:40:36737)
    at Oi (index-9a9c449b.js:38:3279)
    at index-9a9c449b.js:40:34263
overrideMethod @ console.js:288
i1 @ index-9a9c449b.js:40
o.componentDidCatch.n.callback @ index-9a9c449b.js:40
HT @ index-9a9c449b.js:38
iR @ index-9a9c449b.js:40
SF @ index-9a9c449b.js:40
uV @ index-9a9c449b.js:40
mV @ index-9a9c449b.js:40
Wi @ index-9a9c449b.js:40
cR @ index-9a9c449b.js:40
Oi @ index-9a9c449b.js:38
(anonymous) @ index-9a9c449b.js:40
setTimeout
(anonymous) @ index-9a9c449b.js:40
p4 @ index-9a9c449b.js:40
NR @ index-9a9c449b.js:40
s @ index-9a9c449b.js:40
a @ index-9a9c449b.js:40
eo @ index-9a9c449b.js:40
setData @ index-9a9c449b.js:40
onSuccess @ index-9a9c449b.js:40
g @ index-9a9c449b.js:40
Promise.then
b @ index-9a9c449b.js:40
m4 @ index-9a9c449b.js:40
fetch @ index-9a9c449b.js:40
ku @ index-9a9c449b.js:40
onSubscribe @ index-9a9c449b.js:40
subscribe @ index-9a9c449b.js:40
(anonymous) @ index-9a9c449b.js:40
V$ @ index-9a9c449b.js:38
wm @ index-9a9c449b.js:40
Fl @ index-9a9c449b.js:40
mV @ index-9a9c449b.js:40
Wi @ index-9a9c449b.js:40
cR @ index-9a9c449b.js:40
Oi @ index-9a9c449b.js:38
(anonymous) @ index-9a9c449b.js:40
Show 1 more frame
Show lessUnderstand this error
index-9a9c449b.js:59 React Router caught the following error during render TypeError: Cannot assign to read only property '0' of string 'Stack'
    at code (index-9a9c449b.js:204:14984)
    at RC (index-9a9c449b.js:38:19538)
    at AF (index-9a9c449b.js:40:44055)
    at kF (index-9a9c449b.js:40:39787)
    at pV (index-9a9c449b.js:40:39715)
    at wg (index-9a9c449b.js:40:39568)
    at y1 (index-9a9c449b.js:40:35933)
    at cR (index-9a9c449b.js:40:36737)
    at Oi (index-9a9c449b.js:38:3279)
    at index-9a9c449b.js:40:34263 {componentStack: '\n    at code (http://192.168.64.4:30886/assets/ind…86/assets/index-9a9c449b.js:40:148114)\n    at sTe'}

**Please describe your setup**
- Server setup using k8s

**Comment by raolak** [comment]
We can close this iss
