### ISSUE TITLE
"API call didn't return a message" error repeating very frequently in v5.5, with openai.

### ISSUE THREAD

**Issue by HG2407** [letta-ai/letta#2255]
**Describe the bug**
The issue is "API call didn't return a message", error is repeating very frequently with letta v5.5. I am using openai's gpt 4o. The problem is that the inner monologue is displayed everytime on the ui but there is no actual user response given. I have been able to debug the issue. It is because in the normal response, when everything is correct, the message.choices contains tool calls for send message. But whenever this issue arises the message.choices doesn't contain any function call. It should have been fixed according to a previous closed bug. But it is still there and is very frustating. I am attaching the logs as well.
```
correct normal response:
original response choices in unpack_all_inner_thoughts_from_kwargs: {
    "id": "message-fd4674bd-0943-4372-a1bd-55f84da2175d",
    "choices": [
        {
            "finish_reason": "tool_calls",
            "index": 0,
            "message": {
                "content": null,
                "tool_calls": [
                    {
                        "id": "6b6fe6f1-3edb-4a3a-b775-e0edd",
                        "type": "function",
                        "function": {
                            "arguments": "{\"inner_thoughts\":\"Keeping the interaction engaging. Ensuring consistency in responding to Harshit.\",\"message\":\"Hey there, Harshit! Let me know if there's anything specific you need or if you'd just like to chat.\"}",
                            "name": "send_message"
                        }
                    }
                ],
                "role": "assistant",
                "function_call": null
            },
            "logprobs": null,
            "seed": null
        }
    ],
    "created": "2024-12-15T19:25:37.356338Z",
    "model": "gpt-4o-2024-08-06",
    "system_fingerprint": "fp_a79d8dac1f",
    "object": "chat.completion",
    "usage": {
        "completion_tokens": 48,
        "prompt_tokens": 15582,
        "total_tokens": 15630
    }
}
_get_ai_reply response: {
    "id": "message-fd4674bd-0943-4372-a1bd-55f84da2175d",
    "choices": [
        {
            "finish_reason": "tool_calls",
            "index": 0,
            "message": {
                "content": "Keeping the interaction engaging. Ensuring consistency in responding to Harshit.",
                "tool_calls": [
                    {
                        "id": "6b6fe6f1-3edb-4a3a-b775-e0edd",
                        "type": "function",
                        "function": {
                            "arguments": "{\n  \"message\": \"Hey there, Harshit! Let me know if there's anything specific you need or if you'd just like to chat.\"\n}",
                            "name": "send_message"
                        }
                    }
                ],
                "role": "assistant",
                "function_call": null
            },
            "logprobs": null,
            "seed": null
        }
    ],
    "created": "2024-12-15T19:25:37.356338Z",
    "model": "gpt-4o-2024-08-06",
    "system_fingerprint": "fp_a79d8dac1f",
    "object": "chat.completion",
    "usage": {
        "completion_tokens": 48,
        "prompt_tokens": 15582,
        "total_tokens": 15630
    }
}
```

```
error causing response:
original response choices in unpack_all_inner_thoughts_from_kwargs: {
    "id": "message-4c44f4dd-95d5-45c1-ac8f-0c118a5b2967",
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "Hello again, Harshit! 👋 How can I assist you today? 😊",
                "tool_calls": null,
                "role": "assistant",
                "function_call": null
            },
            "logprobs": null,
            "seed": null
        }
    ],
    "created": "2024-12-15T19:20:23.558565Z",
    "model": "gpt-4o-2024-08-06",
    "system_fingerprint": "fp_a79d8dac1f",
    "object": "chat.completion",
    "usage": {
        "completion_tokens": 17,
        "prompt_tokens": 8289,
        "total_tokens": 8306
    }
}
_get_ai_reply response: {
    "id": "message-4c44f4dd-95d5-45c1-ac8f-0c118a5b2967",
    "choices": [
        null
    ],
    "created": "2024-12-15T19:20:23.558565Z",
    "model": "gpt-4o-2024-08-06",
    "system_fingerprint": "fp_a79d8dac1f",
    "object": "chat.completion",
    "usage": {
        "completion_tokens": 17,
        "prompt_tokens": 8289,
        "total_tokens": 8306
    }
}
```

**Please describe your setup**
- [x] How did you install letta?
  - `pip install letta`? `pip install letta-nightly`? `git clone`?
  - git clone
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
  - Ubuntu
  - How are you running `letta`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)
  - poetry run letta server

**Screenshots**
correct response:
<img width="815" alt="Screenshot 2024-12-16 at 1 31 25 AM" src="https://github.com/user-attachments/assets/a8cc3cb8-9ba1-453e-8a02-37f22675927f" />
error response:
<img width="817" alt="Screenshot 2024-12-16 at 1 32 19 AM" src="https://github.com/user-attachments/assets/ed4fcf41-80c2-4a3e-95f8-2cdb228066e1" />

**Additional context**
I have also modified the parameters of _get_ai_reply, a little:
```
def _get_ai_reply(
        self,
        message_sequence: List[Message],
        function_call: str = "auto",
        first_message: bool = False,  # hint
        stream: bool = False,  # TODO move to config?
        fail_on_empty_response: bool = True, # this was initially False
        empty_response_retry_limit: int = 0 # this was initially 3
    ) -> ChatCompletionResponse:
```

**Letta Config**
Please attach your `~/.letta/config` file or copy past it below.

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run Letta with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by cpacker** [comment]
Are you able to reproduce this error in the latest version?

**Comment by HG2407** [comment]
Should I try with the latest version ? because this thing should have been fixed way before v5.5, so I am not sure.

**Comment by cpacker** [comment]
If you're able to reproduce with the latest version that would be great and help us debug the ticket faster (if the bug is still happening), whereas we're not able to actively debug issues for older version (eg v0.5.5)

**Comment by cpacker** [comment]
> But whenever this issue arises the message.choices doesn't contain any function call

For example I don't think this should be happening when we use structured outputs, which should be on by default for `gpt-4o-2024-08-06` in the latest version (but I'm not sure about v0.5.5).

**Comment by AliSayyah** [comment]
I have the exact issue with version 0.6.5 for existing agents. new agents work fine.

**Comment by AliSayyah** [comment]
Tested the 0.6.6 and the issue still remains.

**Comment by HG2407** [comment]
I suspect this error is arising because we are trying to make openai call the send message which is a custom function we have provided, but due to the system message, agent persona and human persona added to the context of the current message, which may include 2-3 function calls, leads to context limit being filled in openai. leading to the send message not being called. just a thought.

**Comment by cpacker** [comment]
> I suspect this error is arising because we are trying to make openai call the send message which is a custom function we have provided, but due to the system message, agent persona and human persona added to the context of the current message, which may include 2-3 function calls, leads to context limit being filled in openai. leading to the send message not being called. just a thought.

I don't think this is the case since OpenAI throws a special context overflow related error when this happens, which Letta has a special catch for (` "finish_reason": "stop",` will be something specific).

> Tested the 0.6.6 and the issue still remains.

@AliSayyah interesting - so you get this error on old agents, but not new agents. Are you able to share more details about the agent payloads?

For example, it would really help debug if you're able to share the output of `/dumpraw` in the Letta CLI for both the old agents that aren't working, and the new agents that are working. That might help us ID if the issue has to do with something in the context window (or it could be a model setting being off and not triggering the same backend settings?).

**Comment by HG2407** [comment]
@cpacker does your latest pr solve the issue ? Can you explain how you solved it ?

**Comment by cpacker** [comment]
@HG2407 / @AliSayyah yep I think the PR should fix the bug! Basically, there was a bug in the interpretation of some API calls that were missing tool calls, which turns the entire message choice into null, instead of just the tool choice section.

Will be part of the next release which should be out asap!

**Comment by AliSayyah** [comment]
@cpacker I tried the nightly build and the issue remains, unfortunately.

**Comment by HG2407** [comment]
I can confirm @cpacker

**Comment by cpacker** [comment]
@AliSayyah @HG2407 are either of you able to provide me a quick way to reproduce the issue on the latest docker or source?

For example, something like:
1. Run `docker run` with latest nightly
2. Create a new agent (select X starter kit) in the ADE
3. Set model to `gpt-4o-mini`
4. Say "Y" in the chat
5. ^if you do (4) N times, you'll reproduce the error

**Comment by AliSayyah** [comment]
@cpacker I haven't found any particular pattern to reproduce it, but I'll try again today.

**Comment by HG2407** [comment]
@cpacker this issue usually arises when the agent needs to call two three functions in one go, sequentially. At that time, usually 2-3 functions are called then the request ends.

**Comment by AliSayyah** [comment]
```
 Letta.letta.server.server - ERROR - Error in server._step: HTTP error occurred: 400 Client Error: Bad Request for url: https://api.openai.com/v1/chat/completions | Status code: 400, Message: {
   "error": {
     "message": "Invalid value for 'content': expected a string, got null.",
     "type": "invalid_request_error",
     "param": "messages.[161].content",
     "code": null
   }
 }
 Traceback (most recent call last):
   File "/app/letta/llm_api/helpers.py", line 142, in make_post_request
     response.raise_for_status()
   File "/app/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
     raise HTTPError(http_error_msg, response=self)
```
On the latest version (0.6.7) I get this error message. maybe a different issue?

**Comment by cpacker** [comment]
interesting - @AliSayyah is it possible to share the payload (request) going to OpenAI here? Feel free to replace any sensitive strings - I'm more curious how this payload ended up happening.

Is it a `user` role message that's empty? Is it an `assistant` role message that has no tools + no content? (since I think no content is fine if there's tools?)

**Comment by cpacker** [comment]
Also - is the agent here effectively "bricked"? E.g. every step/message causes this error? Or is it stochastic?

**Comment by AliSayyah** [comment]
> interesting - @AliSayyah is it possible to share the payload (request) going to OpenAI here? Feel free to replace any sensitive strings - I'm more curious how this payload ended up happening.
> 
> Is it a `user` role message that's empty? Is it an `assistant` role message that has no tools + no content? (since I think no content is fine if there's tools?)

Do I need to edit the source code to do this?is there an easier way?

and this error raises every step.

**Comment by AliSayyah** [comment]
@cpacker I forgot to tag you, sorry.
