### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by hherpa** [letta-ai/letta#712]
**Describe the bug**
I'm trying to figure out how to use memgpt in autogen, but when I run the standard script, I get an error.

**Please describe your setup**

- [ ] MemGPT version - 0.2.10
- [ ] How did you install memgpt?
  - `pip install pymemgpt`
- [ ] Describe your setup
  - Windows
  - cmd.exe

**Screenshots**
![image](https://github.com/cpacker/MemGPT/assets/146547175/61a4207b-47ee-4a4c-b4da-bc2d2fea022d)
![image](https://github.com/cpacker/MemGPT/assets/146547175/a6d55d23-0ae6-4f33-afe8-fe519bf21efc)

**Additional context**

- [ ] i use mistral-7b
- [ ] I am running mistral-7b via text-generation-webui and using their "openai" API
- [ ] requests come to google colab from webui, but an error is displayed in the terminal

**the whole text of the error**

```
The agent 'user_proxy' has an empty system_message, and may not work well with GroupChat.
GroupChat select_speaker failed to resolve the next speaker's name. This is because the speaker selection OAI call returned:
Thank you for the instruction. I will make sure to complete the task you have assigned to me. If you require any further assistance or additional information from me, please don't hesitate to let me know.
Traceback (most recent call last):
  File "C:\Users\akidra\Desktop\autogen_hub\test.py", line 58, in <module>
    user_proxy.initiate_chat(
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\autogen\agentchat\conversable_agent.py", line 550, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\autogen\agentchat\conversable_agent.py", line 348, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\autogen\agentchat\conversable_agent.py", line 481, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\autogen\agentchat\conversable_agent.py", line 906, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\autogen\agentchat\groupchat.py", line 271, in run_chat
    reply = speaker.generate_reply(sender=self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\autogen\agentchat\conversable_agent.py", line 906, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\autogen\memgpt_agent.py", line 314, in _generate_reply_for_user_message
    ) = self.agent.step(user_message, first_message=False, skip_verify=self.skip_verify)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\agent.py", line 676, in step
    raise e
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\agent.py", line 595, in step
    response = self.get_ai_reply(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\agent.py", line 805, in get_ai_reply
    raise e
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\agent.py", line 786, in get_ai_reply
    response = create(
               ^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\openai_tools.py", line 361, in wrapper
    raise e
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\openai_tools.py", line 334, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\openai_tools.py", line 384, in create
    return openai_chat_completions_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\openai_tools.py", line 171, in openai_chat_completions_request
    url = smart_urljoin(url, "chat/completions")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akidra\AppData\Roaming\Python\Python311\site-packages\memgpt\openai_tools.py", line 66, in smart_urljoin
    if not base_url.endswith("/"):
           ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**my code**
```
# $env:OPENAI_API_KEY="https://enable-describing-organizing-flyer.trycloudflare.com"
from memgpt.autogen.memgpt_agent import create_memgpt_autogen_agent_from_config
import autogen

config_list = [
    {
        "model": "mistral-7b",
        "base_url": "https://radio-directory-chart-largest.trycloudflare.com/v1",
        "api_key": "NULL",
    }
]

llm_config = {"config_list": config_list, "seed": 42, "max_tokens": 10000, "timeout": 10000}

# create a config for the MemGPT AutoGen agent
config_list_memgpt = [
    {
        "model": "mistral-7b",
        "context_window": 8192,
        "preset": "memgpt_chat",  # NOTE: you can change the preset here
        # OpenAI specific
        "model_endpoint_type": "openai",
        "openai_key": "https://radio-directory-chart-largest.trycloudflare.com/v1",
    },
]
llm_config_memgpt = {"config_list": config_list_memgpt, "seed": 42}

# there are some additional options to do with how you want the interface to look (more info below)
interface_kwargs = {
    "debug": False,
    "show_inner_thoughts": True,
    "show_function_outputs": False,
}

critic = autogen.AssistantAgent(
    name = "Critic",
    system_message="""Critic. test prompt
""",
    llm_config = llm_config,
)

# then pass the config to the constructor
memgpt_autogen_agent = create_memgpt_autogen_agent_from_config(
    "MemGPT_agent",
    llm_config=llm_config_memgpt,
    system_message=f"Your desired MemGPT persona",
    interface_kwargs=interface_kwargs,
    default_auto_reply="...",
    skip_verify=False,  # NOTE: you should set this to True if you expect your MemGPT AutoGen agent to call a function other than send_message on the first turn
)

user_proxy = autogen.UserProxyAgent(
    "user_proxy", code_execution_config={"work_dir": "coding"})

groupchat = autogen.GroupChat(agents=[user_proxy, memgpt_autogen_agent, critic], messages=[], max_round=12)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

user_proxy.initiate_chat(
    manager, message="""test prompt
""")
```

**Comment by cpacker** [comment]
Should be fixed, please open if not, thank you <3
