### ISSUE TITLE
Error: `First message function call wasn't send_message or archival_memory_search: content=None` when re-loading agent

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#972]
**Describe the bug**
I re-loaded an agent after attaching some data, but got this error immediately when running `memgpt run` again. 

**Please describe your setup**

- [x] MemGPT version: 0.3.0
- [x] How did you install memgpt? git clone
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)? Mac
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal) Shell 

**Screenshots**
```
First message function call wasn't send_message or archival_memory_search: content=None
tool_calls=[ToolCall(id='call_p2QEsO8wJB046uJcZZryaMDD', type='function', function=FunctionCall(arguments='{\n  "content": "The
copyright for \'The Hobbit\' is held by George Allen & Unwin Ltd.",\n  "request_heartbeat": false\n}',
name='archival_memory_insert'))] role='assistant' function_call=None
Using model openai, endpoint: https://api.openai.com/v1
Sending request to https://api.openai.com/v1/chat/completions
response = <Response [200]>
response.json = {'id': 'chatcmpl-8q5CSlFZ1fAXnGK837HMA7ARHR8wR', 'object': 'chat.completion', 'created': 1707423736, 'model':
'gpt-4-0613', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': None, 'tool_calls': [{'id':
'call_RNTXGoSbgrV8Q27tp79EZx6K', 'type': 'function', 'function': {'name': 'archival_memory_insert', 'arguments': '{\n  "content":
"The copyright for \'The Hobbit\' is held by George Allen & Unwin Ltd.",\n  "request_heartbeat": false\n}'}}]}, 'logprobs': None,
'finish_reason': 'tool_calls'}], 'usage': {'prompt_tokens': 4576, 'completion_tokens': 41, 'total_tokens': 4617},
'system_fingerprint': None}
First message function call wasn't send_message or archival_memory_search: content=None
tool_calls=[ToolCall(id='call_RNTXGoSbgrV8Q27tp79EZx6K', type='function', function=FunctionCall(arguments='{\n  "content": "The
copyright for \'The Hobbit\' is held by George Allen & Unwin Ltd.",\n  "request_heartbeat": false\n}',
name='archival_memory_insert'))] role='assistant' function_call=None
Using model openai, endpoint: https://api.openai.com/v1
Sending request to https://api.openai.com/v1/chat/completions
response = <Response [200]>
response.json = {'id': 'chatcmpl-8q5CV9RJABQW5axHPERcYs4WPWHQq', 'object': 'chat.completion', 'created': 1707423739, 'model':
'gpt-4-0613', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': None, 'tool_calls': [{'id':
'call_pA3O9g1lIKV4MuYiLFaZpvzv', 'type': 'function', 'function': {'name': 'archival_memory_insert', 'arguments': '{\n  "content":
"The copyright for \'The Hobbit\' is held by George Allen & Unwin Ltd.",\n  "request_heartbeat": false\n}'}}]}, 'logprobs': None,
'finish_reason': 'tool_calls'}], 'usage': {'prompt_tokens': 4576, 'completion_tokens': 41, 'total_tokens': 4617},
'system_fingerprint': None}
First message function call wasn't send_message or archival_memory_search: content=None
tool_calls=[ToolCall(id='call_pA3O9g1lIKV4MuYiLFaZpvzv', type='function', function=FunctionCall(arguments='{\n  "content": "The
copyright for \'The Hobbit\' is held by George Allen & Unwin Ltd.",\n  "request_heartbeat": false\n}',
name='archival_memory_insert'))] role='assistant' function_call=None
step() failed
user_message = None
error = Hit first message retry limit (10)
step() failed with an unrecognized exception: 'Hit first message retry limit (10)'
An exception occurred when running agent.step():
Traceback (most recent call last):
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/main.py", line 347, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/main.py", line 323, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/agent.py", line 673, in step
    raise e
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/agent.py", line 602, in step
    raise Exception(f"Hit first message retry limit ({first_message_retry_limit})")
Exception: Hit first message retry limit (10)
```

**Comment by hmlatapie** [comment]
I'm seeing what appears to be the same issue on Ubuntu. using chromadb/persistent, sqlite.
![image](https://github.com/cpacker/MemGPT/assets/4633080/8872be4f-6540-4f64-b141-7a9af52147d5)

![image](https://github.com/cpacker/MemGPT/assets/4633080/1384a263-a5de-49dd-8c4f-6ce2c04a5824)

Note that token utilization can skyrocket and get very expensive with this error. about $10 per crash in my case. Suggest not doing any agent reloads until this is resolved.

**Comment by Elliott-Chong** [comment]
Facing this issue as well

**Comment by louria** [comment]
This happens because verify_first_message_correctness in utils.py enforces certain checks of the1st message response. I ran into this when I told the bot my actual name and the response only includes a core_memory_append function call but no response msg.

**Comment by yoadsn** [comment]
What is the purpose of the verification in the first place? Specifically, why does it make sure there is an internal monologue?
The app does that (as stated above) also when the agent is restarted when the conversation is already mid-way.
So knowing the purpose for that might help improving this and not blindly applying --no-verify on every restart.

**Comment by NovaBro** [comment]
Just wanted to note, still having the same issue now.
The bug is still in the letta version 0.5.0 python version 3.12.4.
